[options]
db_host = localhost
http_interface = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = 0101
http_port = 8099
addons_path = C:\Users\Pasante\odoo\addons,C:\Users\Pasante\odoo\custom_addons
admin_passwd = 0101